- hosts: localhost
  tasks:
  - name: List all resources.
    api: 
      action: GET
      url: "https://jsonplaceholder.typicode.com/posts" 
    register: response

  - debug: 
      var: response

#  - name: GET request lookup.
#    debug: msg="{{ lookup('url', 'https://jsonplaceholder.typicode.com/posts/1', wantlist=True) }}"

  - name: Custom Lookup plugin.
    debug: msg="{{ lookup('lookup_url', 'https://jsonplaceholder.typicode.com/posts/3', wantlist=True) }}"

  - name: Create a resource.
    api:
      action: POST
      url: "https://jsonplaceholder.typicode.com/posts"
      data: '{"title" : "foo", "body" : "bar", "userId" : "1"}'
    register: response
  
  - debug:
      var: response

  - name: Updating a resource.
    api:
      action: PUT
      url: "https://jsonplaceholder.typicode.com/posts/1"
      data: '{"id" : "1", "title" : "foo", "body" : "bar", "userId" : "1"}'
    register: response
  
  - debug:
      var: response

  - name: Patching a resource.
    api:
      action: PATCH
      url: "https://jsonplaceholder.typicode.com/posts/1"
      data: '{"title" : "foo"}'
    register: response
  
  - debug:
      var: response

  - name: Delete all resources.
    api: 
      action: DELETE
      url: "https://jsonplaceholder.typicode.com/posts/1" 
    register: response

  - debug: 
      var: response
