- hosts: localhost
  tasks:
  - name: List all resources.
    api: 
      action: GET
      url: "https://jsonplaceholder.typicode.com/posts" 
    register: response

  - debug: 
      var: response

  - name: Create a resource.
    api:
      action: POST
      url: "https://jsonplaceholder.typicode.com/posts"
      data: '{"id" : "101", "title" : "foo", "body" : "bar", "userId" : "1"}'
      headers: '{"Content-type" : "application/json; charset=UTF-8"}'
    register: response
  
  - debug:
      var: response